version: '3'

volumes:
  mysql_volume:
    driver: local
  wp_volume:
    driver: local

services:
  mysql:
    image: mariadb
    container_name: mariadb
    env_file: .env
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    ports:
      - "3306:3306"
    volumes:
      - mysql_volume:/var/lib/mysql
      - ./requirements/mariadb/conf/my.cnf:/etc/mysql/conf
    restart: always
    networks:
      - localhost

  wordpress:
    image: wordpress
    container_name: wordpress
    depends_on:
      - mysql
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    volumes:
      - wp_volume:/var/www
      - ./requirements/wordpress/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    depends_on:
      - mysql
    links:
      - mysql
    ports:
      - "9000:9000"
    working_dir: /var/www
    restart: on-failure
    networks:
      - localhost

  nginx:
    image: nginx
    container_name: nginx
    depends_on: 
      - wordpress
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    volumes:
      - wp_volume:/var/www
      - ./requirements/nginx/conf/nginx.conf:/etc/nginx/conf
    ports:
      - "443:443"
    restart: on-failure
    networks:
      - localhost

networks:
  localhost:
    name: inet
