version: '3.4'

volumes:
  mysql_volume:
  	name: ${MYSQL_VOL_ID}
	driver: local
  wp_volume:
  	name: ${WP_VOL_ID}

services:
  mysql:
    image: mariadb
    container_name: mariadb
    env_file: .env
    build:
      context: ./requirement/mariadb
      dockerfile: ./requirements/mariadb/Dockerfile
    ports:
      - "3306:3306"
    volumes:
      - mysql_volume:/var/lib/mysql
      - ./requirements/mariadb/conf/my.cnf:/etc/mysql/conf
    restart: always
    networks:
      - app-network

  wordpress:
    image: wordpress:php7.4-fpm
    container_name: wordpress
    volumes:
      - wp_volume:/var/www
      - ./requirements/wordpress/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    depends_on:
      - mysql
    links:
      - mysql
    ports:
      - "9000:9000"
    working_dir: /var/www
    restart: always
    networks:
      - app-network

  nginx:
    image: nginx:debian
    container_name: nginx
    volumes:
      - wp_volume:/var/www
      - ./requirements/nginx/conf/nginx.conf:/etc/nginx/conf
    ports:
      - "80:80"
      - "443:443"
    restart: always
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
