version: "3.9"

services:
  mysql:
    image: mariadb
    volumes:
      - /data/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root42
      MYSQL_DATABASE: db_name
      MYSQL_USER: user42
      MYSQL_PASSWORD: user42
    restart: always
  wordpress:
    image: wordpress:php7.3-fpm-alpine
    volumes:
      - /data/html:/var/www/html
    depends_on:
      - mysql
    environment:
      WORDPRESS_DB_HOST: mysql
      MYSQL_ROOT_PASSWORD: root42
      WORDPRESS_DB_NAME: db_name
      WORDPRESS_DB_USER: user42
      WORDPRESS_DB_PASSWORD: user42
      WORDPRESS_TABLE_PREFIX: wp_
    links:
      - mysql
    restart: always
  nginx:
    image: nginx:debian
    volumes:
      - nginx:/etc/nginx/conf.d
      - /data/html:/var/www/html
    ports:
      - 8080:80
    links:
      - wordpress