version: '3'

volumes:
  mysql_volume:
    driver: local
    driver_opts:
      o: bind
      type: volume
      device: /home/mciupek/data/database
  wp_volume:
    driver: local
    driver_opts:
      o: bind
      type: volume
      device: /home/mciupek/data/website

services:
  mysql:
    image: mariadb:v0
    container_name: mariadb
    env_file: ./.env
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    ports:
      - "3306:3306"
    volumes:
      - mysql_volume:/var/lib/mysql
    restart: on-failure
    networks:
      - network

  wordpress:
    image: wordpress:v0
    container_name: wordpress
    env_file: ./.env
    depends_on:
      - mysql
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    volumes:
      - wp_volume:/var/www
    depends_on:
      - mysql
    ports:
      - "9000:9000"
    working_dir: /var/www
    restart: on-failure
    networks:
      - network

  nginx:
    image: nginx:v0
    container_name: nginx
    env_file: ./.env
    depends_on: 
      - wordpress
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    volumes:
      - wp_volume:/var/www
    ports:
      - "443:443"
    restart: on-failure
    networks:
      - network

networks:
  network:
    name: network
