DELETE FROM	mysql.user WHERE User='${WP_USER}';
DROP DATABASE $MYSQL_DATABASE;
DELETE FROM mysql.db WHERE Db='$MYSQL_DATABASE';
DELETE FROM mysql.user WHERE User='${WP_ADMIN}' AND Host NOT IN ('localhost', '127.0.0.1', '::1');
CREATE USER ${WP_USER}@'%' IDENTIFIED by '${WP_USER_PASSWORD}';
CREATE DATABASE $MYSQL_DATABASE;
GRANT ALL PRIVILEGES ON "${MYSQL_DATABASE}.*" TO "${WP_USER}"@'%';
FLUSH PRIVILEGES;